//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimitesCreditoDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LIMITES_CREDITOS_LIC
    {
        public int IDE_LIMITE_CREDITO { get; set; }
        public int IDE_CONTRATO_TERCEIRO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DAT_EXPIRA_LIMITE { get; set; }
        public string DES_OBSERVACAO { get; set; }
        public int QTD_PARCELAS_APROVACAO { get; set; }
        public decimal VLR_TOTAL_APROVACAO { get; set; }
        public Nullable<decimal> PER_TAXA_OPERACAO { get; set; }
        public Nullable<decimal> VLR_TARIFA_OPERACAO { get; set; }
        public Nullable<decimal> VLR_TOTAL_DESCONTOS { get; set; }
        public decimal VLR_LIQUIDO_APROVACAO { get; set; }
        public Nullable<int> NUM_PARCELA_INICIAL { get; set; }
        public Nullable<int> IDE_MOTIVO { get; set; }
        public string LIS_SITUACAO { get; set; }
        public string NOM_LOGIN_APROVACAO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DAT_APROVACAO { get; set; }
        public string DES_APROVACAO { get; set; }
        public string STS_LIMITE { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DAT_INCLUSAO { get; set; }
        public string NOM_LOGIN_INCLUSAO { get; set; }
        public string NUM_IP_INCLUSAO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DAT_ALTERACAO { get; set; }
        public string NOM_LOGIN_ALTERACAO { get; set; }
    }
}
